# 4.a.

In [23]:
import numpy as np
from sklearn import linear_model

In [24]:
from error_func import rmse_calc, mae_calc

In [40]:
X = [[1.0, 2], [2, 4], [3, 6], [4, 6]]
X = np.array([np.array(i) for i in X])
y = np.array([2, 3, 4, 5])
y = y.reshape((4,1))
print('X:\n',X,'\n')
print('y:\n',y,'\n')

X:
 [[ 1.  2.]
 [ 2.  4.]
 [ 3.  6.]
 [ 4.  6.]] 

y:
 [[2]
 [3]
 [4]
 [5]] 



In [46]:
ridge1 = linear_model.Ridge(alpha=0)
ridge1.fit(X,y)
pred1 = ridge1.predict(X)
print('Ridge Regression coefficients:', ridge1.coef_)
print('Ridge Regression intercept:', ridge1.intercept_)
print('Predictions:\n',pred1,'\n')
print('RMSE = ', rmse_calc(y,pred1))

Ridge Regression coefficients: [[ 1.  0.]]
Ridge Regression intercept: [ 1.]
Predictions:
 [[ 2.]
 [ 3.]
 [ 4.]
 [ 5.]] 

RMSE =  [ 0.]


In [48]:
ridge2 = linear_model.Ridge(alpha=0.5)
ridge2.fit(X,y)
pred2 = ridge2.predict(X)
print('Ridge Regression coefficients:', ridge2.coef_)
print('Ridge Regression intercept:', ridge1.intercept_)
print('Predictions:\n',pred2,'\n')
print('RMSE = ', rmse_calc(y,pred2))

Ridge Regression coefficients: [[ 0.59649123  0.24561404]]
Ridge Regression intercept: [ 0.90350877]
Predictions:
 [[ 1.99122807]
 [ 3.07894737]
 [ 4.16666667]
 [ 4.76315789]] 

RMSE =  [ 0.15015125]


In [50]:
ridge3 = linear_model.Ridge(alpha=3)
ridge3.fit(X,y)
pred3 = ridge3.predict(X)
print('Ridge Regression coefficients:', ridge3.coef_)
print('Ridge Regression intercept:', ridge3.intercept_)
print('Predictions:\n',pred3,'\n')
print('RMSE = ', rmse_calc(y,pred3))

Ridge Regression coefficients: [[ 0.33333333  0.33333333]]
Ridge Regression intercept: [ 1.16666667]
Predictions:
 [[ 2.16666667]
 [ 3.16666667]
 [ 4.16666667]
 [ 4.5       ]] 

RMSE =  [ 0.28867513]


# 4.b.

In [51]:
ridge4 = linear_model.Ridge(alpha=1)
ridge4.fit(X,y)
pred4 = ridge4.predict(X)
print('Ridge Regression coefficients:', ridge4.coef_)
print('Ridge Regression intercept:', ridge4.intercept_)
print('Predictions:\n',pred4,'\n')
print('RMSE = ', rmse_calc(y,pred4))

Ridge Regression coefficients: [[ 0.47826087  0.30434783]]
Ridge Regression intercept: [ 0.93478261]
Predictions:
 [[ 2.02173913]
 [ 3.10869565]
 [ 4.19565217]
 [ 4.67391304]] 

RMSE =  [ 0.1980529]


In [70]:
def summer(a,b,c):
    return a**2+b/(c*2)
l1= l2= l3 = np.array([1,1,2])
#l2 = np.array((4,5,6,4))
la,lb = np.meshgrid(l1,l2)
la

array([[1, 1, 2],
       [1, 1, 2],
       [1, 1, 2]])