In [2]:
import numpy as np 

import pandas as pd

# Q2(a)

In [10]:
def normalEquationRidgeRegression(x, y,lembda):
    x_copy=[]
    for i in x:
        a=[1]+i
        x_copy.append(a)
    #print(x_copy)
    x=x_copy
    x=np.array(x)
    a=x.transpose()
    test=np.dot(a,x)
    
    I = np.identity(len(test), dtype = float) 
    #print(4*I)
    inv = np.linalg.inv(np.dot(a,x)+lembda*I) 
    Y=np.array(y).transpose()
    theta=np.dot(inv,np.dot(a,Y))
    return theta,x



# x=[[1,2,4],[3,3,9],[4,5,7],[2,6,4],[2,6,9]]
# lbd=1
# y=[7,12,16,12,16]
x=[[1],[3],[6]]
y=[6,10,16]
th,x_cop=normalEquationRidgeRegression(x, y,1)
print(th)
print(np.dot(x_cop,th))
#print(t,inv)
#print(np.dot(t,inv))

[2.09090909 2.36363636]
[ 4.45454545  9.18181818 16.27272727]


# Q2(b)

In [11]:
def coodrdinateDescentRegression(x, y, iterations):
    x_copy=[]
    for i in x:
        a=[1]+i
        x_copy.append(a)
    #print(x_copy)
    x=x_copy
    x=np.array(x)
    #print(x)
    
    
    theta=len(x[0])*[0]
    #print(theta)
    
    
    for i in range(iterations):
        theta_j=theta
        for j in range(len(x[1])):
            theta_j=theta ##
            theta_j[j]=0
            #print(theta_j)
            prediction_j = np.dot(x, theta_j) ##
            error_j = y-prediction_j    ##
            #print(x[j])
            #print(error_j)
            x_j=[]          
            
            for m in range(len(x)):
                x_j.append(x[m][j])
                
            x_j=np.array(x_j)
            #print(x_j)
            rho_j=np.dot(x_j,error_j)
            z_j=np.dot(x_j.transpose(),x_j)
            #print(z_j)
            theta_j=rho_j*(float(z_j)**(-1))
            theta[j]=theta_j

    return x,theta
x=[[1,2,4],[3,3,9],[4,5,7],[2,6,4],[2,6,9],[1,5,8]]
lbd=1
y=[7,12,16,12,16,15]
x,th=coodrdinateDescentRegression(x, y,8000)
print(np.dot(x,th))

print(th)

[ 6.80893803 13.00903145 14.8456867  12.87449393 16.57038306 13.89146683]
[0.5372158206166283, 0.5644658984739945, 1.3752725007785733, 0.7391778262223615]


# Q2(c)

In [34]:
def coodrdinatedescentlasso(x, y, delta, iterations):
    x_copy=[]
    for i in x:
        a=[1]+i
        x_copy.append(a)
    x=x_copy
    x=np.array(x)
    theta=len(x[0])*[1000] 
    for i in range(iterations):
        theta_j=theta
        for j in range(len(x[1])):
            theta_j=theta
            theta_j[j]=0
            prediction_j = np.dot(x, theta_j)
            error_j = y-prediction_j
            #error_j = error_j.reshape((len(error_j),1))
            x_j=x[:,j]
            #x_j=x_j.reshape((len(x_j),1))
            rho_j=np.dot(x_j.T,error_j)
            #print(rho_j)
            z_j=np.dot(x_j.transpose(),x_j)
                        
            if rho_j> ((delta**2)/2):
                theta_j=(rho_j-delta**2)/z_j
            elif rho_j< ((-delta**2)/2):
                theta_j=(rho_j+delta**2)/z_j
            else:
                theta_j=0
            theta[j]=theta_j
            
    return x,theta

x=[[1,2,4],[3,3,9],[4,5,7],[2,6,4],[2,6,9],[1,5,8]]
lbd=1
y=[7,12,16,12,16,15]
# x=[[1],[3],[6]]
# y=[6,10,16]
x,th=coodrdinatedescentlasso(x, y,5,50000)
print(np.dot(x,th))
print(th)

[ 6.53402133 13.24442352 12.8916618  10.41968659 16.15867247 14.03945898]
[0, 0, 0.9714163148233617, 1.1477971752873224]


# 2(d)

In [1]:
import random
import numpy as np
x=[[1,2,4],[3,3,9],[4,5,7],[2,6,4],[2,6,9],[1,5,8]]
y=[7,12,16,12,16,15]
alpha = 0.0008
iterations = 1000000
m = len(y)
np.random.seed(1) 
theta = np.random.rand(len(x[0]))
theta=[1.5,1,1]
def sgdregression(x, y, theta, iterations, alpha):
    x=np.array(x)
    for i in range(iterations):
        num=random.randint(0,len(x)-1)
        x_n=x[num]
        #print(x_n)
        prediction=np.dot(x_n,theta)
        #print(prediction)
        error=prediction-y[num]
        normal=np.dot(x_n,x_n)     
        theta=theta -(((alpha)*error)*x_n)/normal
    return theta

theta=sgdregression(x, y, theta, iterations, alpha)
print(theta)

print(np.dot(x,theta))

[0.53750183 1.33286297 0.86435627]
[ 6.66065284 13.3903008  14.86481602 12.52960653 16.85138787 14.11666681]


# 2(e)

In [ ]:
def costlasso(x,y,theta):
    cost=0
    for i in theta:
        cost=cost+abs(i)
        
    
    return cost
    

import numpy as np
x=[[1,2,3],[1,3,5],[1,2,1],[1,10,12],[4,21,9]]
y=[6,9,4,30,40]
alpha = 0.01
iterations = 500000
m = len(y)
np.random.seed(1) 
theta = np.random.rand(len(x[0]))
theta=[2,2,2]
def gradient_descent(x, y, theta,alpha,labd, iterations):
    x=np.array(x)
    cost_prev=0
    cost=0
    for i in range(iterations):
        prediction = np.dot(x, theta)
        #print(prediction)
        cost_prev=cost
        error = prediction - y
        cost = np.sqrt( np.dot(error.transpose(), error))/m
        theta = theta - (alpha * (1/m) * np.dot(x.transpose(), error)) 
        #print(theta)
    return theta

theta=gradient_descent(x, y, theta, iterations, alpha)
print(theta)
x=[[1,2,3],[1,3,5],[1,2,1],[1,10,12],[4,21,9]]
print(np.dot(x,theta))